### ISSUE TITLE
Handle non-JSON responses

### ISSUE THREAD

**Issue by the-kenny** [exthereum/ethereumex#18]
I'm having some issues using a pretty loaded geth-node as the rpc server. It seems like sometimes it doesn't return a json body, causing https://github.com/exthereum/ethereumex/blob/master/lib/ethereumex/http_client.ex#L24 to error out with an `Undefined token on position 0` error in `Poison.decode!`, crashing the server. If `ethereumex` is under load and crashes more than 5 times in a quick succession, it brings down the whole `ethereumex` application (and the whole VM if it's running in `MIX_ENV=prod`).

One solution would be using the `with` macro in `decode_body` and `post_request`, gracefully propagating http- as well as parsing errors. This would make the whole system much more robust.

**Comment by ayrat555** [comment]
@the-kenny you already described solution to this problem. would you mind making a PR with it?

**Comment by the-kenny** [comment]
I'll try to fix it & open a PR in the next few days :)
