### ISSUE TITLE
Generic Client Protocol

### ISSUE THREAD

**Issue by hswick** [exthereum/ethereumex#23]
It would be great if there was a generic client protocol that could be implemented by specific providers, like http, websocket, and ipc. It seems that a lot of the code for this to happen already exists, but a found a few difficulties when trying to extend this library with a  websocket client. 

1. The supervisor tree has the HttpClient hardcoded into it. 
2. When implementing the WebSocketClient module, I wasn't sure where I should put `WebSockex.start_link("ws://*url*", __MODULE__, state)` since the GenServer details are abstracted away by Ethereumex.Client.Server

This issue probably relates to #8 as well, in that a generic client would allow for a client to simply implement the protocol. Also, I have Ethereumex.HttpClient hardcoded in a bunch of places in ExW3, which isn't ideal.

Ideally the API would be similar to web3.js where the user can manually set the provider url and type.

**Comment by ayrat555** [comment]
I think this issue is resolved
