### ISSUE TITLE
Any reason to not include personal too ? 

### ISSUE THREAD

**Issue by eduardonunesp** [exthereum/ethereumex#3]

**Comment by ayrat555** [comment]
@eduardonunesp I didn't understand the question. Can you give a little more explanation?

**Comment by eduardonunesp** [comment]
Sure, I mean the personal methods like the methods in `web3`. Like `unlockAccount` for instance. https://github.com/ethereum/web3.js/blob/develop/lib/web3/methods/personal.js

**Comment by ayrat555** [comment]
@eduardonunesp There are too many implementations of ethereum's json rpc api so it will be quite hard to maintain all their custom api methods.

I guess I can add some basic method that you can call like
```
 Ethereumex.HttpClient.request(method_name, params)
```

Is it ok for you?

**Comment by izelnakri** [comment]
I think the current implementation encourages people to have create their own wallets, and secure them and sign transactions on their own. Unlocking wallets, get them to their ethereum client and sendTransaction method might be convenient for starters but it comes with security problems. I'm actually glad that we dont have the _personal methods. They are also not part of the ethereum JSON RPC but web3.

**Comment by izelnakri** [comment]
@eduardonunesp if you are interested in sending signed transactions via elixir you can check my ```eth``` hex library however it is very early stage/unstable.

**Comment by ayrat555** [comment]
@eduardonunesp if you are interested in sending signed transactions via elixir you can check izelnakri's eth hex library however it is very early stage/unstable

**Comment by ayrat555** [comment]
@izelnakri https://github.com/exthereum/ethereumex/pull/4 what do you think?

**Comment by eduardonunesp** [comment]
Thanks @izelnakri and @ayrat555 that's all and makes sense to me, case closed here :+1:
