### ISSUE TITLE
serializing constructor for smartcontract?

### ISSUE THREAD

**Issue by vans163** [exthereum/ethereumex#32]
Is there a way to serialize the constructor like here?
https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L36L46

**Comment by hswick** [comment]
Hi @vans163 you may be interested in my library that is a higher level wrapper around ethereumex, it supports constructor arguments https://github.com/hswick/exw3

**Comment by vans163** [comment]
@hswick il check it out more. The thing that bugs me is the native lib (libsecp256k1), im wondering what kind of nightmares will happen if i try to build an erlang release on windows.
