### ISSUE TITLE
decode in readme doesnt work

### ISSUE THREAD

**Issue by vans163** [exthereum/ethereumex#33]
To convert the balance into an integer:

balance_bytes
|> String.slice(2..-1)
|> Base.decode16!(case: :lower)
|> TypeDecoder.decode_raw([{:uint, 256}])
|> List.first

If balance is 0 we get "0x0" as the return and we cant pipe that to Base.decode16!(case: :lower) without an error. We need to pad leading zero in this case.

I think a decode/encode function is needed in the library.

**Comment by ayrat555** [comment]
@vans163 It's just an example in README

**Comment by vans163** [comment]
Its such a common procedure, any idea if it should be included in the lib?

**Comment by ayrat555** [comment]
@vans163 Do you mean decoding/encoding hex values?

**Comment by hswick** [comment]
You can simply use https://github.com/exthereum/abi, the separate modules makes sense since it is separate behavior
