### ISSUE TITLE
Multiple endpoints

### ISSUE THREAD

**Issue by ghbutton** [exthereum/ethereumex#35]
Currently, the only way send requests to a node is to set the configuration variable as such: `    Application.put_env(:ethereumex, :url, node)`

Would it be possible to have an option to pass the node on the function call instead of having it at the application level. Something like this: `Ethereumex.HttpClient.eth_gas_price(node: "http://localhost:8545")`

I can help with a PR if you are ok with this option.

**Comment by ayrat555** [comment]
@ghbutton I'm totally ok with this option. Thanks

**Comment by ghbutton** [comment]
https://github.com/exthereum/ethereumex/pull/37

**Comment by ghbutton** [comment]
PR merged
