### ISSUE TITLE
Roadmap schedule / feature completion list

### ISSUE THREAD

**Issue by egalano** [exthereum/ethereumex#9]
Thanks for this your hard work. I've been following this project's progress. Do you have a roadmap document or other release schedule we can look to determine the client's level of maturity? For instance is the JSON RPC implementation fully compatible with https://github.com/ethereum/wiki/wiki/JSON-RPC ?

**Comment by ayrat555** [comment]
@egalano yep, it's fully compatible with official json rpc api. also you can call protocol implementation (parity, geth etc) custom apis with send_request method.

Plans:
1. Finish smart contracts functionality (compilation, deploy, interaction) - PR https://github.com/exthereum/ethereumex/pull/7
2. Implement Ipc client - issue https://github.com/exthereum/ethereumex/issues/8

**Comment by egalano** [comment]
Great news thanks. I'll give it a try.
